on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Flutter SDK
        uses: actions/cache@v3
        id: flutter-cache
        with:
          path: ~/.flutter
          key: flutter-sdk-${{ runner.os }}-3.24.5

      - name: Clone Flutter into Cache if not hit
        if: steps.flutter-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.24.5 --depth 1 ~/.flutter

      - name: Add Flutter to PATH
        run: echo "$HOME/.flutter/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Release)
        run: flutter build apk --release

      - name: Build AppBundle (Release)
        run: flutter build appbundle --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AppBundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-release-appbundle
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Python Dependencies
        run: pip install pyyaml google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client requests speedtest-cli

      - name: Upload Artifacts to Google Drive and Send Telegram Message
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python upload_to_gdrive.py
