name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout source
        uses: actions/checkout@v2

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # Cache Flutter SDK only (not dependencies)
      - name: Cache Flutter SDK
        uses: actions/cache@v3
        id: flutter-cache
        with:
          path: ~/.flutter
          key: flutter-sdk-${{ runner.os }}-3.24.5

      # Clone Flutter SDK into cache folder if cache not hit
      - name: Clone Flutter into ~/.flutter
        if: steps.flutter-cache.outputs.cache-hit != 'true'
        run: git clone https://github.com/flutter/flutter.git --branch 3.24.5 --depth 1 ~/.flutter

      # Add Flutter to PATH for all future steps
      - name: Add Flutter to PATH
        run: echo "$HOME/.flutter/bin" >> $GITHUB_PATH

      # Run flutter pub get
      - name: Install dependencies
        run: flutter pub get

      # Build APK
      - name: Build APK (Release)
        run: flutter build apk --release

      # Build App Bundle
      - name: Build AppBundle (Release)
        run: flutter build appbundle --release

      # Upload APK artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # Upload AAB artifact
      - name: Upload AppBundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-release-appbundle
          path: build/app/outputs/bundle/release/app-release.aab

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      # Install Python dependencies
      - name: Install Python packages
        run: pip install pyyaml google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client requests speedtest-cli

      # Upload to Google Drive + Telegram
      - name: Upload to GDrive & Telegram
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python upload_to_gdrive.py
